# Setup
title:               Woojun Lee
tagline:             'Code study'
description:         '시도 + ing'
url:                 https://wjleekr927.github.io/
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Woojun Lee
  url:               https://velog.io/@wjleekr927
  email:             wjleekr927@kaist.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.4
google_analytics_id: #UA-XXXX-Y
