# Setup
title:               Woojun Lee
tagline:             'Code study'
description:         '추후에 CV를 추가하든 말든 일단은 다른 블로그에서 힘을 기르고 오겠습니다'
url:                 https://wjleekr927.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Woojun Lee
  url:               https://twitter.com/mdo
  email:             wjleekr927@kaist.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
